options(repos='https://cran.rstudio.com')
install.packages('pacman')
library(pacman)
p_load('tidyverse')
# install.packages('devtools')
p_load(char=c('flexdashboard','ggrepel','cowplot','patchwork','ggpubr','shiny'))
p_load(char=c('RColorBrewer','viridis'))
p_load('BiocManager')
p_load('htmlwidgets')
p_load('rio')
p_load('mosaic')
p_load('broom')
p_load('dygraphs')
p_load('nycflights13')
